### ISSUE TITLE
[question] Why did you use base model instead of instructed ones?

### ISSUE THREAD

**Issue by remiconnesson** [TIGER-AI-Lab/LongICLBench#1]
Hello,

I'm curious about the reason to use base models instead of instructed ones? Especially that the proprietary ones have been through this finetuning.

Any reason why?

**Comment by wenhuchen** [comment]
instructed ones are normally weaker at in-context learning due to the SFT stage. Our logic is that: if a model has a base model released, we are gonna use base model. If not, we use the chat model. For the proprietary ones, we don't have their base model, so we need to use their fine-tuned version. I think there was some experiments by Tianle showing that the base model and SFT model are getting roughly the same number on our eval sets.
